### ISSUE TITLE
How to add arguments?

### ISSUE THREAD

**Issue by yitzhakbg** [abiosoft/caddy-git#22]
Not strictly an issue, but rather a question.
Here's what I need:
git clone --depth 1 https://github.com/yitzhakbg/levpoem.git /srv/levpoem

Q: How and where to specify the "--depth 1" arguments?

**Comment by abiosoft** [comment]
Custom parameters are not supported at the moment.

**Comment by yitzhakbg** [comment]
thanks. Kudos on your fine work

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Another problem. Tried using git directive, but it isn't recognized:
    caddy_1   | 2016/01/25 23:14:28 Caddyfile:8 - Parse error: Unknown
    directive 'git'
    Caddyfile:
    ~/S/Sites_common » cat
    docker-caddy/Caddyfile                                                                                                                     
    master ✗
    # http://192.168.99.100, https://192.168.99.100 {
    #   root /var/www/heartbt
    #  tls yitzhakbargeva@gmail.com
    # }
    http://levpoem.co.il, https://levpoem.co.il {
      root /var/www/levpoem
    #  tls off
      git {
        repo https://github.com/yitzhakbg/levpoem.git
        path /src/levpoem
        branch master
    #    args --depth 1
      }
    }
    http://heartbt.co.il, https://heartbt.co.il {
      root /var/www/heartbt
      tls off
    }
    http://46.101.221.201 {
      root /var/www/heartbt
    #  tls off
    }
    On 26/1/16 00:06, Abiola Ibrahim wrote:
    
    
      Custom parameters are not supported at the moment.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    P.S. Git is installed in the container
    
    On 26/1/16 01:19, Yltzhak Bar Geva
      wrote:
    
    
      
      body p { margin-bottom: 0cm; margin-top: 0pt; } 
      Another problem. Tried using git directive, but it isn't
      recognized:
      caddy_1   | 2016/01/25 23:14:28 Caddyfile:8 - Parse error: Unknown
      directive 'git'
      Caddyfile:
      ~/S/Sites_common » cat
      docker-caddy/Caddyfile                                                                                                                     

      master ✗
      # http://192.168.99.100, https://192.168.99.100 {
      #   root /var/www/heartbt
      #  tls yitzhakbargeva@gmail.com
      # }
      http://levpoem.co.il, https://levpoem.co.il {
        root /var/www/levpoem
      #  tls off
        git {
          repo https://github.com/yitzhakbg/levpoem.git
          path /src/levpoem
          branch master
      #    args --depth 1
        }
      }
      http://heartbt.co.il, https://heartbt.co.il {
        root /var/www/heartbt
        tls off
      }
      http://46.101.221.201 {
        root /var/www/heartbt
      #  tls off
      }
      On 26/1/16 00:06, Abiola Ibrahim
        wrote:
      
      
        Custom parameters are not supported at the moment.
        —
          Reply to this email directly or view

            it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Can't figure out how to install git extension
    
    ~/S/Sites_common » caddyext install
    git:github.com:abiosoft/caddy-git
    Caddy's source not found on any $GOPATH directories.
    Set CADDYPATH on your enviroment to a valid caddy source.
    
    but...
    ~/S/Sites_common » echo $CADDYPATH
    /home/ybg/.go/src/github.com/mholt/caddy
    
    and
    ~/S/Sites_common » ls $CADDYPATH
    app  config  dist  middleware  server  appveyor.yml 
    CONTRIBUTING.md  LICENSE.txt  main.go  README.md
    
    What am I doing wrong?
    
    On 26/1/16 00:07, Yltzhak Bar Geva
      wrote:
    
    
      
      thanks. Kudos on your fine work
      
      On 26/1/16 00:06, Abiola Ibrahim
        wrote:
      
      
        Custom parameters are not supported at the moment.
        —
          Reply to this email directly or view

            it on GitHub.

**Comment by abiosoft** [comment]
You need to download Caddy with Git plugin.

Available here via the download page https://caddyserver.com/download/build?os=linux&arch=amd64&features=git..

Or Use caddyext to install it.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Here's what I get:
    ~/S/Sites_common » caddyext install
    git:github.com:abiosoft/caddy-git                                                                                             
    master ✗
    Caddy's source not found on any $GOPATH directories.
    Set CADDYPATH on your enviroment to a valid caddy source.
    ~/S/Sites_common » CADDYPATH=~/.go/src/github.com/caddyserver
    
    I tried numerous combinations of setting CADDYPATH but have not been
    able to find the right one. What should it be?
    
    On 26/1/16 06:40, Abiola Ibrahim wrote:
    
    
      You need to download Caddy with Git plugin.
      Available here via the download page https://caddyserver.com/download/build?os=linux&arch=amd64&features=git..
      Or Use caddyext to install it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by abiosoft** [comment]
`go get github.com/mholt/caddy` should solve it.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Still not. I've tried as many combinations of $CADDYFILE as I can
    think of
    
    ~/S/Sites_common » echo $GOPATH
    /home/ybg/.go
    ~/S/Sites_common » ls $GOPATH
    bin  pkg  src
    ~/S/Sites_common » ls $GOPATH/pkg
    linux_amd64
    ~/S/Sites_common » ls $GOPATH/bin
    caddy  caddydev  caddyext  go-bindata  hugo
    ~/S/Sites_common » ls $GOPATH/src
    bitbucket.org  github.com  golang.org  gopkg.in
    ~/S/Sites_common » ls $GOPATH/src/github.com
    BurntSushi   cpuguy83  dustin  flynn    hacdias    inconshreveable 
    jteeuwen   kr          mholt  mitchellh  PuerkitoBio  russross 
    spf13
    caddyserver  dchest    eknkc   gorilla  hashicorp  jimstudt        
    kardianos  magiconair  miekg  opennota   robfig       shurcooL 
    yosssi
    ~/S/Sites_common » ls $GOPATH/src/github.com/mholt
    caddy  custombuild
    ~/S/Sites_common » CADDYPATH=~/.go/src/github.com/mholt/caddy
    ~/S/Sites_common » caddyext install
    git:github.com:abiosoft/caddy-git
    Caddy's source not found on any $GOPATH directories.
    Set CADDYPATH on your enviroment to a valid caddy source.
    ~/S/Sites_common » CADDYPATH=~/.go/src/github.com/mholt/custombuild
    ~/S/Sites_common » caddyext install
    git:github.com:abiosoft/caddy-git
    Caddy's source not found on any $GOPATH directories.
    Set CADDYPATH on your enviroment to a valid caddy source.
    ~/S/Sites_common »
    
    On 26/1/16 07:55, Abiola Ibrahim wrote:
    
    go get github.com/mholt/caddy

**Comment by abiosoft** [comment]
Do you really need to build from source ?

**Comment by abiosoft** [comment]
How many plugins do you want to use with Caddy ?

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    it doesn't matter to me. I thought it would be useful to find the
    solution in order improve the documentation.
    
    On 26/1/16 08:47, Abiola Ibrahim wrote:
    
    
      Do you really need to build from source ?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Let's look at it in a general sense. The plugin concept is a great
    idea, including the git plugin. Others might encounter the same
    problem. I'd like to help in improving the process to make it easy
    for everyone to use all the listed (and future) plugins.
    
    On 26/1/16 08:48, Abiola Ibrahim wrote:
    
    
      How many plugins do you want to use with Caddy ?
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    caddyext
      documentation says that Caddy's source should be in the
    GOPATH. Could it be that something regarding $CADDYFILE or the
    documentation is confusing? Can it be made more user-friendly?
    
    On 26/1/16 07:55, Abiola Ibrahim wrote:
    
    
      go get github.com/mholt/caddy should solve it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks Abiola.
    Where should this be installed? Perhaps the documentation could
    clarify this?
    
    On 26/1/16 06:40, Abiola Ibrahim wrote:
    
    
      You need to download Caddy with Git plugin.
      Available here via the download page https://caddyserver.com/download/build?os=linux&arch=amd64&features=git..
      Or Use caddyext to install it.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by abiosoft** [comment]
I was just wondering what went wrong.

Let's start afresh.

This is actually the easiest way. git and search are optional plugins, you can remove or add more.
```
$ curl https://getcaddy.com | bash -s git,search
```
Building from source. Ensure you have Go and GOPATH is set.
```
$ go get github.com/mholt/caddy
$ go get github.com/caddyserver/caddyext
$ caddyext install git
$ caddyext build
```

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks,
    I've got it running using the custom caddy with git from the
    download page which you sent me but I had to download it manually
    and insert it in the docker build directory because I couldn't find
    the link.
    What would the be the link corresponding to:
    wget
    https://github.com/mholt/caddy/releases/download/v${CADDY_VERSION}/caddy_linux_amd64.tar.gz
    && \
    in the Dockerfile for the custom git caddy. And, how would we do the
    same for other plugins.
    
    I'll do the fresh install you described, but beyond solving my
    problem, don't you think it would be best if we could streamline
    (or, clarify and document) the whole process to make it easier for
    everyone to install plugins in their docker configuration?
    Yitzhak
    
    On 26/1/16 10:00, Abiola Ibrahim wrote:
    
    
      I was just wondering what went wrong.
      Let's start afresh.
      This is actually the easiest way. git and search are optional
        plugins, you can remove or add more.
      $ curl https://getcaddy.com | bash -s git,search

      Building from source. Ensure you have Go and GOPATH is set.
      $ go get github.com/mholt/caddy
$ go get github.com/caddyserver/caddyext
$ caddyext install git
$ caddyext build

      —
        Reply to this email directly or view
          it on GitHub.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Tried it. mean this?
    curl https://getcaddy.com | bash -s
    git,search                                                                                                          
    [NORMAL]
      % Total    % Received % Xferd  Average Speed   Time    Time    
    Time  Current
                                     Dload  Upload   Total   Spent   
    Left  Speed
    100  4099  100  4099    0     0   2420      0  0:00:01  0:00:01
    --:--:--  2419
    Downloading Caddy for darwin/amd64...
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
    Extracting...
    Archive:  /tmp/caddy_darwin_amd64_custom.zip
      inflating: /tmp/caddy
    Putting caddy in /usr/local/bin (may require password)
    Password:
    
    
    Note:
    1. It provides os=darwin. Is that ideal under Linux or in an Alpine
    container?
    2. The features parameters are missing. What should they be if
    configuring manually? I tried with wget and curl:
    
        /jjj » curl
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git,search
        zsh: parse error near `&'
        ~/jjj » curl
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git
        zsh: parse error near `&'
        ~/jjj » curl
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
        zsh: parse error near `&'
        ~/jjj » wget
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
        zsh: parse error near `&'
        ~/jjj » wget
https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git
        zsh: parse error near `&'
    
       When I placed it as URL in the browser, it downloaded OK. Once
    with parameters (larger file) and once without.
    
    3. Watch out for sudo if downlaoding in container. You have to
    install sudo:
    RUN apk add --update wget ca-certificates bash git rsync sudo
    && \
    
    What would the best be for installing in a container?
    
    On 26/1/16 10:00, Abiola Ibrahim wrote:
    
    
      $ curl https://getcaddy.com | bash -s git,search

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    P.S. Wouldn't it be desirable to add parameters to git clone?
    For examle:
    git clone --depth 1 xyz.com
    So as to keep the server free of git bloat?
    
    On 27/1/16 16:09, Yltzhak Bar Geva
      wrote:
    
    
      
      body p { margin-bottom: 0cm; margin-top: 0pt; } 
      Tried it. mean this?
      curl https://getcaddy.com | bash -s
      git,search                                                                                                          

      [NORMAL]
        % Total    % Received % Xferd  Average Speed   Time    Time    
      Time  Current
                                       Dload  Upload   Total   Spent   
      Left  Speed
      100  4099  100  4099    0     0   2420      0  0:00:01  0:00:01
      --:--:--  2419
      Downloading Caddy for darwin/amd64...
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
      Extracting...
      Archive:  /tmp/caddy_darwin_amd64_custom.zip
        inflating: /tmp/caddy
      Putting caddy in /usr/local/bin (may require password)
      Password:
      
      
      Note:
      1. It provides os=darwin. Is that ideal under Linux or in an
      Alpine container?
      2. The features parameters are missing. What should they be if
      configuring manually? I tried with wget and curl:
      
          /jjj » curl
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git,search
          zsh: parse error near `&'
          ~/jjj » curl
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git
          zsh: parse error near `&'
          ~/jjj » curl
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
          zsh: parse error near `&'
          ~/jjj » wget
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=
          zsh: parse error near `&'
          ~/jjj » wget
      https://caddyserver.com/download/build?os=darwin&arch=amd64&features=git
          zsh: parse error near `&'
      
         When I placed it as URL in the browser, it downloaded OK. Once
      with parameters (larger file) and once without.
      
      3. Watch out for sudo if downlaoding in container. You have to
      install sudo:
      RUN apk add --update wget ca-certificates bash git rsync sudo
      && \
      
      What would the best be for installing in a container?
      
      On 26/1/16 10:00, Abiola Ibrahim
        wrote:
      
      
        $ curl https://getcaddy.com | bash -s git,search

**Comment by abiosoft** [comment]
I'll consider adding the ability to add parameters. Note that it is not a priority and I can not guarantee how soon.

If you're having issues with containers and you're not adding anything extra other than Caddy, there are existing containers you can use. https://github.com/mholt/caddy#docker-container.

Thanks.
